version: '3'
services:
  #application dockerfile is in the same folder which is .
  app:
    build: .

  #db is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always